---
title: "stat445_a3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## STAT 445 Assignment 3


There are 42 observations from a bivariate normal distribution. The sample mean is given by $\bar{x} = \begin{bmatrix} 0.0564 \\ 0.603 \end{bmatrix}$. The sample variance is given by  $S = \begin{bmatrix} 0.0144 && 0.0117 \\ 0.0117 && 0.0146 \end{bmatrix}$ .
```{r}
S = matrix(c(0.0144, 0.0117, 0.0117, 0.0146), 2, 2)
S
xbar = matrix(c(0.564, 0.603), 2, 1)
xbar
```

## Question 1

a) Find the 95% confidence region for the mean vector $\mu = \begin{bmatrix} \mu_{1} \\ \mu_{2} \end{bmatrix}$.

```{r}
install.packages("ellipse")
library(ellipse)
```


```{r}
plot(ellipse(S/42, centre=xbar, t=sqrt(((2*41)/40)*qf(0.95, 2, 40) )), type="l", xlim=c(0.51, 0.630), ylim=c(0.5, 0.70))
abline(h=0.565)
abline(h=0.641)
abline(v=0.527)
abline(v=0.601)

abline(v=0.521, lty=2)
abline(v=0.607, lty=2)
abline(h=0.560, lty=2)
abline(h=0.646, lty=2)


```

## Question 2
a)
```{r}
fat_dat <- read.table("~/Documents/SFU/STAT445/a1/fat_dat.txt", quote="\"", comment.char="")
colMeans(fat_dat)
var(fat_dat)
n <- nrow(fat_dat)
ncol(fat_dat)
si <- diag(var(fat_dat))
t <- matrix(qt(0.975, df=nrow(fat_dat)-1), 19, 1)
cbind(colMeans(fat_dat) - t*sqrt(si/n), colMeans(fat_dat) + t*sqrt(si/n))

```


b)

```{r}
fat_dat[, c(11, 12)]
variance <- var(fat_dat[,c(11,12)])
means <- colMeans(fat_dat[,c(11,12)])
means
variance
n
head(fat_dat)
plot(ellipse(variance/n, centre=means, t=sqrt(((2*(n-1)/(n-2))*qf(0.95, 2, n-2))))
     ,type="l")
```
c) Bonferroni Confidence Intervals for the 

```{r}
circData <- fat_dat[,10:19]
m <- ncol(circData)
t2 <- -qt(0.05/(2*m), df=n-1, lower.tail=TRUE)
intervals <- rbind(colMeans(circData) - t2*sqrt(diag(var(circData))/n), colMeans(circData) + t2*sqrt(diag(var(circData))/n))

chestInt <- intervals[,2]
chestInt[1]
abInt <- intervals[,3]
abInt
```

d)
```{r}
plot(ellipse(variance/n, centre=means, t=sqrt(((2*(n-1)/(n-2))*qf(0.95, 2, n-2))))
     ,type="l", xlim=c(99, 103), ylim=c(90, 95))
abline(v=chestInt[1])
abline(v=chestInt[2])
abline(h=abInt[1])
abline(h=abInt[2])
```

e) 
